# Create the k8s namespace for goserv
apiVersion: v1
kind: Namespace
metadata:
  name: goserv

---
# Create an ArgoGD project for goserv
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: goserv-proj
  namespace: argocd
spec:
  description: ArgoCD project for goserv application
  sourceRepos:
    - 'oci://ttl.sh/charts/goserv'
    - 'https://github.com/jpbarto/argocd-eval.git'
  destinations:
    - namespace: goserv
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: '*'
      kind: 'Event'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goserv
  namespace: argocd
spec:
  project: goserv-proj
  sources:
    - repoURL: 'oci://ttl.sh/charts/goserv'
      chart: goserv
      targetRevision: 1.0.13
      helm:
        valueFiles:
          - $values/env-values.yaml
    - repoURL: 'https://github.com/jpbarto/argocd-eval.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: goserv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
